### PR TITLE
Separate RadioInterface class and the QML layout

### PR DESCRIPTION
**Pull request by viktorgino**
Hi

First of all: Great project, you've done exactly what I was about to do. Thanks ! 😄

In this PR I've included a few changes that'd allow the QML layout to be independent from the RadioInterface class.

### CODE REVIEW

**Comment by AlbrechtL** [comment]
Hi,
Welcome to the welle.io development.
Thanks for the code review and the enhancements.

**Comment by AlbrechtL** [comment]
Did you test the changes under Windows?

Today I run it with Windows 10 and welle.io crashes immediately with a segfault after selection a station. The backtrace shows nonsense.

**Comment by viktorgino** [comment]
I tested it on Ubuntu, but I'll try to run it on Windows soon

**Comment by viktorgino** [comment]
Builds and runs nicely on Windows 10, built the latest master with MinGW5.3 and Qt5.7.1 using the libraries from https://github.com/AlbrechtL/welle.io-win-libs.git however I don't have sound. What does the backtrace show in Qt Creator?

**Comment by AlbrechtL** [comment]
I changed to sound output from portaudio to QMultimedia to reduce 3rd party lib dependency. Maybe something goes wrong on Windows. I will check this.

**Comment by AlbrechtL** [comment]
It was an issue on my side. Audio is now working under Windows.

**Pull request merged**
