### PR TITLE
Add ubuntu-toolchain-r/ppa and install latest gcc 4.9

### PR DESCRIPTION
**Pull request by viktorgino**

### CODE REVIEW

**Comment by AlbrechtL** [comment]
Thanks!

**Comment by AlbrechtL** [comment]
Sadly it is still not working `error: ‘make_unique’ is not a member of ‘std`. 
If you like you can look for a solution.
https://travis-ci.org/AlbrechtL/welle.io/jobs/263899049

**Comment by viktorgino** [comment]
It didn't install gcc from the ppa properly, I'll have a play around with it later.

**Comment by mpbraendli** [comment]
I also struggled to get proper C++11 support in Travis-CI. I ended up using gcc 6 using this script: https://github.com/Opendigitalradio/ODR-DabMux/blob/master/.travis.yml

**Pull request merged**
