### PR TITLE
Add AppStream metadata file for welle-io

### LINKED ISSUE #718: Consider adding AppStream metadata
Thanks for creating this great DAB receiver, I love it! Welle.io does not seem to have any [AppStream metadata](https://freedesktop.org/software/appstream/docs/chap-Quickstart.html) on Linux. Because of this, the package cannot be found in GNOME Software, KDE Discover and other package manager UIs based on AppStream. Please, consider creating the AppStream metainfo file.

### PR DESCRIPTION
**Pull request by AsciiWolf**
Closes #718.

I have also renamed the Flatpak file id to match the AppStream id.

### CODE REVIEW

**Comment by AsciiWolf** [comment]
CI failure looks unrelated.

**Review by AlbrechtL — CHANGES_REQUESTED** [review]
Thanks for the improvement! Can you change this pull request to the next branch, please?

**Comment by AsciiWolf** [comment]
> Thanks for the improvement! Can you change this pull request to the next branch, please?

Done. Hopefully there are no conflicts or other problems. :-)

**Comment by AsciiWolf** [comment]
The PR looks good to merge now. Feel free to let me know if there are any otrher problems. Thanks!

**Comment by AsciiWolf** [comment]
I have changed the `<component type="desktop">` tag to `<component type="desktop-application">`. It should not matter, but `desktop-application` is preferred by the current [AppStream specification](https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Application.html):

> The desktop-application component type is the same as the desktop component type - desktop is the older type identifier for desktop-applications and should not be used for new metainfo files, unless compatibility with very old AppStream tools (pre 2016) is still wanted.

**Review by AlbrechtL — APPROVED** [review]

**Pull request merged**
