### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by FartherOut**
Translation to Norsk Bokmål (nb_NO) of most of the entries.

### CODE REVIEW

**Comment by FartherOut** [comment]
Should the resources.qrc be updated too?

**Comment by AlbrechtL** [comment]
Great for the Norwegian translation! Yes please update the resources.qrc and add your name to the file AUTHORS.

**Comment by AlbrechtL** [comment]
BTW: You can update this pull request.

**Comment by FartherOut** [comment]
Updated authors and resources file.
Also updated my translations.

**Comment by AlbrechtL** [comment]
Now try the nightly builds "20171126_5070c1d_xxx" under https://bintray.com/albrechtl/welle.io/welle.io_nightly#files

**Comment by FartherOut** [comment]
Tried it on Win10-x64 and Kubuntu 17.10-x64 and they both works.
It autodetects my language on win10, which is kind of annoying since I always use english anyway :grin:

**Pull request merged**
