### PR TITLE
welle-cli: add option to manually select driver

### PR DESCRIPTION
**Pull request by seife**
This allows to select rtl_tcp driver. Also allow passing
host and port to rtl_tcp.

### CODE REVIEW

**Comment by AlbrechtL** [comment]
Thanks for the new pull request!

**Comment by AlbrechtL** [comment]
@mpbraendli Please review the code as well. For me it looks like what we want.

**Comment by seife** [comment]
rebased on next branch, added Section to README.

**Comment by seife** [comment]
Just an Idea: maybe this could be extended to get rid of the special SoapySDR options

     -s ARGS SoapySDR Driver arguments.
     -A ANT  set input antenna to ANT (for SoapySDR input only).

I'll look into SoapySDR and if wanted can probably prepare a followup patch for this.

**Comment by mpbraendli** [comment]
> Just an Idea: maybe this could be extended to get rid of the special SoapySDR options
> 
> ```
>  -s ARGS SoapySDR Driver arguments.
>  -A ANT  set input antenna to ANT (for SoapySDR input only).
> ```

I agree for the `-s` option, because that overlaps with your newly added option. For the antenna, maybe it's okay to keep it separate, because it might be relevant to other drivers too. But I'll let you investigate and decide!

**Pull request merged**
