### PR TITLE
Fix QT_NO_SYSTEMTRAYICON define and add QUIET_MPG123 flag to mpg123 init

### PR DESCRIPTION
**Pull request by viktorgino**
Hi

When building QT_NO_SYSTEMTRAYICON set I get some include errors, this fixes that. Also added a QUIET_MPG123 so mpg123 output can be muted.

### CODE REVIEW

**Review by AlbrechtL — CHANGES_REQUESTED** [review]
Two things.
1. Please change to the next branch.
2. I don't understand why you need these fixes. Under which circumstances do you are getting compiler errors?

**Comment by gvanem** [comment]
@AlbrechtL Since `QSystemTrayIcon::ActivationReason` is unknown when thee is no `#include <QSystemTrayIcon>`. 
That should be obvious. Try building with it.

**Comment by AlbrechtL** [comment]
Your fix isn't working see here for example: https://app.travis-ci.com/github/AlbrechtL/welle.io/jobs/544182349

**Comment by AlbrechtL** [comment]
Closed because of inactivity.

**Pull request closed without merging**
