### PR TITLE
Warning that Pulseaudio must be installed; don't report that English translation is missing

### PR DESCRIPTION
**Pull request by MichalLeonBorsuk**
Hi, I have added two things: 
* info on Linux that PulseAudio must be installed, otherwise sound does not work without a clear reason
* on systems, where LC_LANG is already English, don't complain about lack of translation

PS sorry for the commits with edits, those got under the radar.

### CODE REVIEW

**Comment by MichalLeonBorsuk** [comment]
Hi, just to bring to your attention that you may have a bug in the CI around flatpack: 

```
$ sudo flatpak --user install welle-repo io.welle.welle-gui
Looking for matches…
io.welle.welle-gui permissions:
    network       pulseaudio            wayland               x11
    dri           file access [1]       dbus access [2]
    [1] host, xdg-config/kdeglobals:ro
    [2] com.canonical.AppMenu.Registrar
        ID                    Branch    Op   Remote       Download
 1.     io.welle.welle-gui    master    i    welle-repo   < 14.8 MB
Proceed with these changes to the user installation? [Y/n]: 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```

**Review by TheButcher80 — APPROVED** [review]

**Review by AlbrechtL — APPROVED** [review]

**Review by AlbrechtL — CHANGES_REQUESTED** [review]
Thanks! One remark. Please change your pull request to the next branch.

**Comment by AlbrechtL** [comment]
> Hi, just to bring to your attention that you may have a bug in the CI around flatpack:
> 
> ```
> $ sudo flatpak --user install welle-repo io.welle.welle-gui
> Looking for matches…
> io.welle.welle-gui permissions:
>     network       pulseaudio            wayland               x11
>     dri           file access [1]       dbus access [2]
>     [1] host, xdg-config/kdeglobals:ro
>     [2] com.canonical.AppMenu.Registrar
>         ID                    Branch    Op   Remote       Download
>  1.     io.welle.welle-gui    master    i    welle-repo   < 14.8 MB
> Proceed with these changes to the user installation? [Y/n]: 
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
> Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
> The build has been terminated
> ```

Thanks for the hint. If you like you can fix it.

**Comment by AlbrechtL** [comment]
Closed because of inactivity.

**Pull request closed without merging**
