### PR TITLE
install welle-io.desktop

### PR DESCRIPTION
**Pull request by meeuw**
install welle-io.desktop during `make install`

### CODE REVIEW

**Comment by mpbraendli** [comment]
Thanks for the patch. There's another file that would need installation, but I've never looked into how to do it, you could maybe help me.

In the `next` branch, cmake can also compile welle-cli. The webserver inside welle-cli currently also needs the `index.html` file to reside in the current working directory. So right now, `make install` doesn't really work for welle-cli, because the html file doesn't get copied anywhere, and welle-cli would anyway not look at the right spot.

Where is the right place to install this file? Can we do it cross-platform?

@AlbrechtL do we need CMake to work under windows too?

**Comment by meeuw** [comment]
I will have a look at welle-cli and have a look where index.html should be installed.

I don't think any Windows user would expect `make install` to work outside the WSL (Windows Subsystem for Linux)

I'd also like to install the welle-io icon to the right directory.

**Comment by mpbraendli** [comment]
I know some are using MinGW, and I know CMake can also output msbuild files (or was it Visual Studio solutions?). However, I don't know if a) it's technically possible b) we want to do it. I don't see a need, but that's only my opinion.

Keep us updated through this pull request.

**Comment by meeuw** [comment]
@mpbraendli I've added index.{html,js} and the application icons, I've also made it possible to manually define GIT_COMMIT_HASH and GIT_DESCRIBE (for building using a tar ball, without git available).

**Comment by AlbrechtL** [comment]
From my point of view there is no need to make cmake work under Windows. The current code doesn't work with MSVC and I don't plan to support it and MinGW is supported by QT Creator and qmake out-of-the box. For welle-cli I don't see to support native Windows because of the special use case. Does welle-cli does work with WSL?

**Comment by meeuw** [comment]
I haven't tried WSL but I will try it when I encounter a Windows 10 machine.
Do you require more changes to this PR before it can be merged? I've set the next branch as target for this PR.

**Comment by meeuw** [comment]
I've tried compiling welle.io on WSL (Debian) but I couldn't install the qt5-charts-dev package (not available). So maybe I'll try another distribution to see if that works.

**Comment by mpbraendli** [comment]
Can you try compiling only welle-cli?

I'll look into reviewing and merging the PR in the next couple of days.

**Comment by mpbraendli** [comment]
I've merged your PR, thanks. Do you know how the application can find out where the application data resides? I don't want to hard-code this into the source.

**Comment by AlbrechtL** [comment]
@meeuw Thanks for trying to compile welle-io under WSL. But much more interesting is welle-cli because for welle-io there exists a native port.

**Comment by meeuw** [comment]
>I've merged your PR, thanks. Do you know how the application can find out where the application data resides? I don't want to hard-code this into the source.

I suppose you can pass `${CMAKE_INSTALL_DATAROOTDIR}/welle-io/html/` to the compiler as a define from CMakefile.

**Pull request merged**
