### PR TITLE
Backport to Android API 21, add close button and fix background service language

### PR DESCRIPTION
**Pull request by twoofseven**

### CODE REVIEW

**Comment by AlbrechtL** [comment]
Thanks for the changes.
Unfortunately the driver install message if no rtl_tcp_andro- driver is installed disappeared. If would be nice if you take a look what is going wrong.

**Comment by twoofseven** [comment]
The message is not yet implemented due to the separation of the activity and the background service. But it is on my todo list.

**Comment by AlbrechtL** [comment]
Ah Ok. Then I will wait for a release until this message is back. In my option this message is mandatory for new users.

**Comment by AlbrechtL** [comment]
BTW: Great improvements!

**Comment by AlbrechtL** [comment]
From one tester I got back the following screen shot.
screenshot_20170918-165741
welle.io is running and usable but the notifications always showed "DAB not initialised" and no buttons appears.

**Comment by twoofseven** [comment]
Interesting. Can you please provide more details about the preconditions, error path (detailed description to reproduce the issue, if possible), and most helpful adb logcat trace?

**Pull request merged**
