### PR TITLE
 Use Android Support Libraries to ensure backward compatibility

### PR DESCRIPTION
**Pull request by twoofseven**
In general the change should ensure backward compatibility as described here: https://developer.android.com/topic/libraries/support-library/index.html

I also moved the  release of resources into the onDestroy() method. This should guarantee that these resource are release properly.

Can you please check whether this still compiles with your environment?

### CODE REVIEW

**Comment by AlbrechtL** [comment]
Which is the lowest supported Android version, now?

**Comment by twoofseven** [comment]
According to the Android developer website “Android 4.0 (API level 14)”, but I do not have a device to test this.

**Comment by AlbrechtL** [comment]
With Android 4.4 welle.io crashes with the following messages:
 ```
D/dalvikvm( 2719): Not late-enabling CheckJNI (already on)
I/ActivityManager( 1624): Start proc io.welle.welle for activity io.welle.welle/org.qtproject.qt5.android.bindings.QtActivity: pid=2719 uid=10057 gids={50057, 3003}
E/jdwp    ( 2719): Failed sending reply to debugger: Broken pipe
D/dalvikvm( 2719): Debugger has detached; object registry had 1 entries
D/dalvikvm( 2719): GC_CONCURRENT freed 299K, 11% free 3208K/3572K, paused 0ms+0ms, total 2ms
D/dalvikvm( 2719): WAIT_FOR_CONCURRENT_GC blocked 2ms
D/dalvikvm( 2719): GC_CONCURRENT freed 347K, 12% free 3270K/3684K, paused 0ms+2ms, total 3ms
D/dalvikvm( 2719): GC_CONCURRENT freed 412K, 13% free 3274K/3752K, paused 0ms+0ms, total 2ms
D/dalvikvm( 2719): GC_CONCURRENT freed 401K, 13% free 3273K/3752K, paused 1ms+1ms, total 5ms
D/dalvikvm( 2719): GC_CONCURRENT freed 418K, 13% free 3274K/3756K, paused 0ms+1ms, total 4ms
D/dalvikvm( 2719): GC_CONCURRENT freed 488K, 17% free 3200K/3844K, paused 1ms+0ms, total 2ms
D/dalvikvm( 2719): WAIT_FOR_CONCURRENT_GC blocked 2ms
D/dalvikvm( 2719): Trying to load lib /data/data/io.welle.welle/lib/libgnustl_shared.so 0x9d019680
D/dalvikvm( 2719): Added shared lib /data/data/io.welle.welle/lib/libgnustl_shared.so 0x9d019680
D/dalvikvm( 2719): No JNI_OnLoad found in /data/data/io.welle.welle/lib/libgnustl_shared.so 0x9d019680, skipping init
D/dalvikvm( 2719): Trying to load lib /data/data/io.welle.welle/lib/libQt5Core.so 0x9d019680
D/dalvikvm( 2719): Added shared lib /data/data/io.welle.welle/lib/libQt5Core.so 0x9d019680
I/QtCore  ( 2719): Start
D/dalvikvm( 2719): Trying to load lib /data/data/io.welle.welle/lib/libQt5Network.so 0x9d019680
D/dalvikvm( 2719): Added shared lib /data/data/io.welle.welle/lib/libQt5Network.so 0x9d019680
D/dalvikvm( 2719): No JNI_OnLoad found in /data/data/io.welle.welle/lib/libQt5Network.so 0x9d019680, skipping init
D/dalvikvm( 2719): Trying to load lib /data/data/io.welle.welle/lib/libQt5Qml.so 0x9d019680
D/dalvikvm( 2719): Added shared lib /data/data/io.welle.welle/lib/libQt5Qml.so 0x9d019680
D/dalvikvm( 2719): No JNI_OnLoad found in /data/data/io.welle.welle/lib/libQt5Qml.so 0x9d019680, skipping init
D/dalvikvm( 2719): Trying to load lib /data/data/io.welle.welle/lib/libQt5Gui.so 0x9d019680
D/dalvikvm( 2719): Added shared lib /data/data/io.welle.welle/lib/libQt5Gui.so 0x9d019680
D/dalvikvm( 2719): No JNI_OnLoad found in /data/data/io.welle.welle/lib/libQt5Gui.so 0x9d019680, skipping init
D/dalvikvm( 2719): Trying to load lib /data/data/io.welle.welle/lib/libQt5Quick.so 0x9d019680
D/dalvikvm( 2719): Added shared lib /data/data/io.welle.welle/lib/libQt5Quick.so 0x9d019680
D/dalvikvm( 2719): No JNI_OnLoad found in /data/data/io.welle.welle/lib/libQt5Quick.so 0x9d019680, skipping init
D/dalvikvm( 2719): Trying to load lib /data/data/io.welle.welle/lib/libQt5Widgets.so 0x9d019680
D/dalvikvm( 2719): Added shared lib /data/data/io.welle.welle/lib/libQt5Widgets.so 0x9d019680
D/dalvikvm( 2719): No JNI_OnLoad found in /data/data/io.welle.welle/lib/libQt5Widgets.so 0x9d019680, skipping init
D/dalvikvm( 2719): Trying to load lib /data/data/io.welle.welle/lib/libQt5Charts.so 0x9d019680
D/dalvikvm( 2719): Added shared lib /data/data/io.welle.welle/lib/libQt5Charts.so 0x9d019680
D/dalvikvm( 2719): No JNI_OnLoad found in /data/data/io.welle.welle/lib/libQt5Charts.so 0x9d019680, skipping init
D/dalvikvm( 2719): Trying to load lib /data/data/io.welle.welle/lib/libQt5Multimedia.so 0x9d019680
D/dalvikvm( 2719): Added shared lib /data/data/io.welle.welle/lib/libQt5Multimedia.so 0x9d019680
D/dalvikvm( 2719): No JNI_OnLoad found in /data/data/io.welle.welle/lib/libQt5Multimedia.so 0x9d019680, skipping init
D/dalvikvm( 2719): Trying to load lib /data/data/io.welle.welle/lib/libQt5RemoteObjects.so 0x9d019680
D/dalvikvm( 2719): Added shared lib /data/data/io.welle.welle/lib/libQt5RemoteObjects.so 0x9d019680
D/dalvikvm( 2719): No JNI_OnLoad found in /data/data/io.welle.welle/lib/libQt5RemoteObjects.so 0x9d019680, skipping init
D/dalvikvm( 2719): Trying to load lib /data/data/io.welle.welle/lib/libQt5AndroidExtras.so 0x9d019680
D/dalvikvm( 2719): Added shared lib /data/data/io.welle.welle/lib/libQt5AndroidExtras.so 0x9d019680
D/dalvikvm( 2719): No JNI_OnLoad found in /data/data/io.welle.welle/lib/libQt5AndroidExtras.so 0x9d019680, skipping init
D/dalvikvm( 2719): Trying to load lib /data/data/io.welle.welle/lib/libQt5QuickParticles.so 0x9d019680
D/dalvikvm( 2719): Added shared lib /data/data/io.welle.welle/lib/libQt5QuickParticles.so 0x9d019680
D/dalvikvm( 2719): No JNI_OnLoad found in /data/data/io.welle.welle/lib/libQt5QuickParticles.so 0x9d019680, skipping init
D/dalvikvm( 2719): Trying to load lib /data/data/io.welle.welle/lib/libQt5MultimediaQuick_p.so 0x9d019680
D/dalvikvm( 2719): Added shared lib /data/data/io.welle.welle/lib/libQt5MultimediaQuick_p.so 0x9d019680
D/dalvikvm( 2719): No JNI_OnLoad found in /data/data/io.welle.welle/lib/libQt5MultimediaQuick_p.so 0x9d019680, skipping init
D/dalvikvm( 2719): Trying to load lib /data/data/io.welle.welle/lib/libQt5QuickTemplates2.so 0x9d019680
D/dalvikvm( 2719): Added shared lib /data/data/io.welle.welle/lib/libQt5QuickTemplates2.so 0x9d019680
D/dalvikvm( 2719): No JNI_OnLoad found in /data/data/io.welle.welle/lib/libQt5QuickTemplates2.so 0x9d019680, skipping init
D/dalvikvm( 2719): Trying to load lib /data/data/io.welle.welle/lib/libQt5QuickControls2.so 0x9d019680
D/dalvikvm( 2719): Added shared lib /data/data/io.welle.welle/lib/libQt5QuickControls2.so 0x9d019680
D/dalvikvm( 2719): No JNI_OnLoad found in /data/data/io.welle.welle/lib/libQt5QuickControls2.so 0x9d019680, skipping init
D/dalvikvm( 2719): Trying to load lib /data/data/io.welle.welle/qt-reserved-files/plugins/platforms/android/libqtforandroid.so 0x9d019680
D/dalvikvm( 2719): Added shared lib /data/data/io.welle.welle/qt-reserved-files/plugins/platforms/android/libqtforandroid.so 0x9d019680
I/Qt      ( 2719): qt start
D/dalvikvm( 2719): Trying to load lib /data/data/io.welle.welle/qt-reserved-files/plugins/bearer/libqandroidbearer.so 0x9d019680
D/dalvikvm( 2719): Added shared lib /data/data/io.welle.welle/qt-reserved-files/plugins/bearer/libqandroidbearer.so 0x9d019680
D/dalvikvm( 2719): No JNI_OnLoad found in /data/data/io.welle.welle/qt-reserved-files/plugins/bearer/libqandroidbearer.so 0x9d019680, skipping init
D/dalvikvm( 2719): Trying to load lib /data/data/io.welle.welle/lib/libQt5QuickParticles.so 0x9d019680
D/dalvikvm( 2719): Shared lib '/data/data/io.welle.welle/lib/libQt5QuickParticles.so' already loaded in same CL 0x9d019680
D/dalvikvm( 2719): Trying to load lib /data/data/io.welle.welle/qt-reserved-files/plugins/mediaservice/libqtmedia_android.so 0x9d019680
D/dalvikvm( 2719): Added shared lib /data/data/io.welle.welle/qt-reserved-files/plugins/mediaservice/libqtmedia_android.so 0x9d019680
D/dalvikvm( 2719): Trying to load lib /data/data/io.welle.welle/lib/libQt5MultimediaQuick_p.so 0x9d019680
D/dalvikvm( 2719): Shared lib '/data/data/io.welle.welle/lib/libQt5MultimediaQuick_p.so' already loaded in same CL 0x9d019680
W/System.err( 2719): java.lang.ClassNotFoundException: android.graphics.drawable.RippleDrawable
W/System.err( 2719): 	at java.lang.Class.classForName(Native Method)
W/System.err( 2719): 	at java.lang.Class.forName(Class.java:251)
W/System.err( 2719): 	at java.lang.Class.forName(Class.java:216)
W/System.err( 2719): 	at org.qtproject.qt5.android.ExtractStyle.getClass(ExtractStyle.java:395)
W/System.err( 2719): 	at org.qtproject.qt5.android.ExtractStyle.<init>(ExtractStyle.java:98)
W/System.err( 2719): 	at org.qtproject.qt5.android.QtActivityDelegate.loadApplication(QtActivityDelegate.java:605)
W/System.err( 2719): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 2719): 	at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err( 2719): 	at org.qtproject.qt5.android.bindings.QtLoader.loadApplication(QtLoader.java:237)
W/System.err( 2719): 	at org.qtproject.qt5.android.bindings.QtLoader.startApp(QtLoader.java:649)
W/System.err( 2719): 	at org.qtproject.qt5.android.bindings.QtActivityLoader.onCreate(QtActivityLoader.java:183)
W/System.err( 2719): 	at org.qtproject.qt5.android.bindings.QtActivity.onCreateHook(QtActivity.java:266)
W/System.err( 2719): 	at org.qtproject.qt5.android.bindings.QtActivity.onCreate(QtActivity.java:273)
W/System.err( 2719): 	at android.app.Activity.performCreate(Activity.java:5231)
W/System.err( 2719): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
W/System.err( 2719): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
W/System.err( 2719): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
W/System.err( 2719): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
W/System.err( 2719): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
W/System.err( 2719): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 2719): 	at android.os.Looper.loop(Looper.java:136)
W/System.err( 2719): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
W/System.err( 2719): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 2719): 	at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err( 2719): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
W/System.err( 2719): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
W/System.err( 2719): 	at dalvik.system.NativeStart.main(Native Method)
W/System.err( 2719): Caused by: java.lang.NoClassDefFoundError: android/graphics/drawable/RippleDrawable
W/System.err( 2719): 	... 27 more
W/System.err( 2719): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.graphics.drawable.RippleDrawable" on path: DexPathList[[zip file "/data/app/io.welle.welle-1.apk"],nativeLibraryDirectories=[/data/app-lib/io.welle.welle-1, /vendor/lib, /system/lib]]
W/System.err( 2719): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
W/System.err( 2719): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
W/System.err( 2719): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
W/System.err( 2719): 	... 27 more
W/System.err( 2719): java.lang.ClassNotFoundException: android.graphics.drawable.AnimatedStateListDrawable
W/System.err( 2719): 	at java.lang.Class.classForName(Native Method)
W/System.err( 2719): 	at java.lang.Class.forName(Class.java:251)
W/System.err( 2719): 	at java.lang.Class.forName(Class.java:216)
W/System.err( 2719): 	at org.qtproject.qt5.android.ExtractStyle.getClass(ExtractStyle.java:395)
W/System.err( 2719): 	at org.qtproject.qt5.android.ExtractStyle.<init>(ExtractStyle.java:99)
W/System.err( 2719): 	at org.qtproject.qt5.android.QtActivityDelegate.loadApplication(QtActivityDelegate.java:605)
W/System.err( 2719): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 2719): 	at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err( 2719): 	at org.qtproject.qt5.android.bindings.QtLoader.loadApplication(QtLoader.java:237)
W/System.err( 2719): 	at org.qtproject.qt5.android.bindings.QtLoader.startApp(QtLoader.java:649)
W/System.err( 2719): 	at org.qtproject.qt5.android.bindings.QtActivityLoader.onCreate(QtActivityLoader.java:183)
W/System.err( 2719): 	at org.qtproject.qt5.android.bindings.QtActivity.onCreateHook(QtActivity.java:266)
W/System.err( 2719): 	at org.qtproject.qt5.android.bindings.QtActivity.onCreate(QtActivity.java:273)
W/System.err( 2719): 	at android.app.Activity.performCreate(Activity.java:5231)
W/System.err( 2719): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
W/System.err( 2719): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
W/System.err( 2719): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
W/System.err( 2719): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
W/System.err( 2719): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
W/System.err( 2719): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 2719): 	at android.os.Looper.loop(Looper.java:136)
W/System.err( 2719): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
W/System.err( 2719): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 2719): 	at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err( 2719): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
W/System.err( 2719): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
W/System.err( 2719): 	at dalvik.system.NativeStart.main(Native Method)
W/System.err( 2719): Caused by: java.lang.NoClassDefFoundError: android/graphics/drawable/AnimatedStateListDrawable
W/System.err( 2719): 	... 27 more
W/System.err( 2719): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.graphics.drawable.AnimatedStateListDrawable" on path: DexPathList[[zip file "/data/app/io.welle.welle-1.apk"],nativeLibraryDirectories=[/data/app-lib/io.welle.welle-1, /vendor/lib, /system/lib]]
W/System.err( 2719): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
W/System.err( 2719): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
W/System.err( 2719): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
W/System.err( 2719): 	... 27 more
W/System.err( 2719): java.lang.ClassNotFoundException: android.graphics.drawable.VectorDrawable
W/System.err( 2719): 	at java.lang.Class.classForName(Native Method)
W/System.err( 2719): 	at java.lang.Class.forName(Class.java:251)
W/System.err( 2719): 	at java.lang.Class.forName(Class.java:216)
W/System.err( 2719): 	at org.qtproject.qt5.android.ExtractStyle.getClass(ExtractStyle.java:395)
W/System.err( 2719): 	at org.qtproject.qt5.android.ExtractStyle.<init>(ExtractStyle.java:100)
W/System.err( 2719): 	at org.qtproject.qt5.android.QtActivityDelegate.loadApplication(QtActivityDelegate.java:605)
W/System.err( 2719): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 2719): 	at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err( 2719): 	at org.qtproject.qt5.android.bindings.QtLoader.loadApplication(QtLoader.java:237)
W/System.err( 2719): 	at org.qtproject.qt5.android.bindings.QtLoader.startApp(QtLoader.java:649)
W/System.err( 2719): 	at org.qtproject.qt5.android.bindings.QtActivityLoader.onCreate(QtActivityLoader.java:183)
W/System.err( 2719): 	at org.qtproject.qt5.android.bindings.QtActivity.onCreateHook(QtActivity.java:266)
W/System.err( 2719): 	at org.qtproject.qt5.android.bindings.QtActivity.onCreate(QtActivity.java:273)
W/System.err( 2719): 	at android.app.Activity.performCreate(Activity.java:5231)
W/System.err( 2719): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
W/System.err( 2719): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
W/System.err( 2719): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
W/System.err( 2719): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
W/System.err( 2719): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
W/System.err( 2719): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 2719): 	at android.os.Looper.loop(Looper.java:136)
W/System.err( 2719): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
W/System.err( 2719): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 2719): 	at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err( 2719): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
W/System.err( 2719): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
W/System.err( 2719): 	at dalvik.system.NativeStart.main(Native Method)
W/System.err( 2719): Caused by: java.lang.NoClassDefFoundError: android/graphics/drawable/VectorDrawable
W/System.err( 2719): 	... 27 more
W/System.err( 2719): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.graphics.drawable.VectorDrawable" on path: DexPathList[[zip file "/data/app/io.welle.welle-1.apk"],nativeLibraryDirectories=[/data/app-lib/io.welle.welle-1, /vendor/lib, /system/lib]]
W/System.err( 2719): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
W/System.err( 2719): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
W/System.err( 2719): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
W/System.err( 2719): 	... 27 more
W/ResourceType( 2719): Skipping entry 0x1080526 in package table 0 because it is not complex!
D/dalvikvm( 2719): GC_CONCURRENT freed 333K, 14% free 3311K/3844K, paused 0ms+1ms, total 4ms
D/dalvikvm( 2719): GC_FOR_ALLOC freed 30K, 13% free 3399K/3868K, paused 1ms, total 1ms
D/dalvikvm( 2719): GC_FOR_ALLOC freed 32K, 12% free 3517K/3964K, paused 1ms, total 1ms
D/dalvikvm( 2719): GC_FOR_ALLOC freed 190K, 11% free 3643K/4084K, paused 2ms, total 2ms
D/dalvikvm( 2719): GC_FOR_ALLOC freed 273K, 12% free 3618K/4100K, paused 1ms, total 1ms
I/dalvikvm-heap( 2719): Grow heap (frag case) to 3.849MB for 267300-byte allocation
D/dalvikvm( 2719): GC_FOR_ALLOC freed <1K, 12% free 3878K/4364K, paused 1ms, total 1ms
D/dalvikvm( 2719): GC_FOR_ALLOC freed 18K, 12% free 3860K/4364K, paused 1ms, total 1ms
I/dalvikvm-heap( 2719): Grow heap (frag case) to 4.085MB for 267300-byte allocation
D/dalvikvm( 2719): GC_FOR_ALLOC freed <1K, 11% free 4121K/4628K, paused 3ms, total 3ms
D/dalvikvm( 2719): GC_FOR_ALLOC freed <1K, 11% free 4121K/4628K, paused 1ms, total 1ms
I/dalvikvm-heap( 2719): Grow heap (frag case) to 4.340MB for 267300-byte allocation
D/dalvikvm( 2719): GC_FOR_ALLOC freed <1K, 11% free 4382K/4892K, paused 1ms, total 1ms
D/dalvikvm( 2719): GC_FOR_ALLOC freed <1K, 11% free 4383K/4892K, paused 2ms, total 2ms
I/dalvikvm-heap( 2719): Grow heap (frag case) to 4.596MB for 267300-byte allocation
D/dalvikvm( 2719): GC_FOR_ALLOC freed <1K, 10% free 4644K/5156K, paused 1ms, total 1ms
D/dalvikvm( 2719): GC_FOR_ALLOC freed <1K, 10% free 4645K/5156K, paused 1ms, total 1ms
I/dalvikvm-heap( 2719): Grow heap (frag case) to 4.852MB for 267300-byte allocation
D/dalvikvm( 2719): GC_FOR_ALLOC freed <1K, 10% free 4906K/5420K, paused 1ms, total 1ms
D/dalvikvm( 2719): GC_FOR_ALLOC freed <1K, 10% free 4906K/5420K, paused 1ms, total 1ms
I/dalvikvm-heap( 2719): Grow heap (frag case) to 5.107MB for 267300-byte allocation
D/dalvikvm( 2719): GC_FOR_ALLOC freed <1K, 10% free 5167K/5684K, paused 2ms, total 2ms
D/dalvikvm( 2719): GC_FOR_ALLOC freed <1K, 9% free 5429K/5948K, paused 1ms, total 1ms
D/dalvikvm( 2719): GC_FOR_ALLOC freed 212K, 9% free 5710K/6212K, paused 2ms, total 2ms
D/dalvikvm( 2719): GC_CONCURRENT freed 322K, 7% free 6231K/6660K, paused 1ms+0ms, total 3ms
D/dalvikvm( 2719): GC_CONCURRENT freed 409K, 7% free 6882K/7356K, paused 1ms+0ms, total 2ms
D/dalvikvm( 2719): WAIT_FOR_CONCURRENT_GC blocked 1ms
D/dalvikvm( 2719): GC_CONCURRENT freed 623K, 9% free 7483K/8172K, paused 1ms+0ms, total 4ms
D/dalvikvm( 2719): GC_CONCURRENT freed 1131K, 14% free 7807K/9000K, paused 2ms+1ms, total 5ms
D/dalvikvm( 2719): GC_CONCURRENT freed 1347K, 15% free 8018K/9432K, paused 1ms+1ms, total 5ms
D/dalvikvm( 2719): GC_FOR_ALLOC freed 431K, 13% free 8523K/9752K, paused 2ms, total 2ms
D/dalvikvm( 2719): Trying to load lib /data/app-lib/io.welle.welle-1/libwelle-io.so 0x9d019680
D/dalvikvm( 2719): Added shared lib /data/app-lib/io.welle.welle-1/libwelle-io.so 0x9d019680
D/dalvikvm( 2719): No JNI_OnLoad found in /data/app-lib/io.welle.welle-1/libwelle-io.so 0x9d019680, skipping init
D/dalvikvm( 2719): GC_FOR_ALLOC freed 6486K, 67% free 3372K/9924K, paused 2ms, total 2ms
I/dalvikvm-heap( 2719): Grow heap (frag case) to 10.245MB for 7225356-byte allocation
D/dalvikvm( 2719): GC_FOR_ALLOC freed 17K, 39% free 10411K/16984K, paused 3ms, total 3ms
D/dalvikvm( 2719): GC_CONCURRENT freed 16K, 39% free 10394K/16984K, paused 0ms+1ms, total 3ms
D/        ( 2719): HostConnection::get() New Host Connection established 0xb8b996e0, tid 2719
D/EGL_emulation( 2719): eglCreateContext: 0xb8cb4560: maj 2 min 0 rcv 2
D/EGL_emulation( 2719): eglMakeCurrent: 0xb8cb4560: ver 2 0
E/EGL_emulation( 2719): tid 2719: eglSurfaceAttrib(1199): error 0x3009 (EGL_BAD_MATCH)
W/HardwareRenderer( 2719): Backbuffer cannot be preserved
D/OpenGLRenderer( 2719): Enabling debug mode 0
D/welle.io( 2719): (null):0 ((null)): main: Run as application, pid: 2719
D/welle.io( 2719): (null):0 ((null)): main: Set language "en_US"
D/welle.io( 2719): (null):0 ((null)): main: Error while loading language "en_US" use English "en_GB" instead
I/ActivityManager( 1624): START u0 {cmp=io.welle.welle/.DabDelegate} from pid 2719
F/libc    ( 2719): Fatal signal 8 (SIGFPE) at 0xb7772ac8 (code=1), thread 2750 (io.welle.welle)
I/DEBUG   ( 1176): pid: 2719, tid: 2750, name: io.welle.welle  >>> io.welle.welle <<<
D/Zygote  ( 1179): Process 2719 terminated by signal (8)
I/ActivityManager( 1624): Process io.welle.welle (pid 2719) has died.
 ```

**Comment by twoofseven** [comment]
Can you please try #221

**Comment by twoofseven** [comment]
Sorry, I thought the issue has been solved. But this was not the case. Therefore I closed the pull request #221.
Have you used the Android Emulator to test the app?

**Comment by AlbrechtL** [comment]
Yes, I use an Android 4.4 emulator but I also have a real Android 4.4 device.

**Comment by twoofseven** [comment]
Sorry, but after I recognised that the original idea behind commit https://github.com/AlbrechtL/welle.io/pull/221/commits/068f860b6d5fbed79ed95f84ec1be3d1c8deb771 was not the solution and the app is still not working within the Android emulator, I thought it is better to test with a real device.
I was able to get a Samsung S3 with Android version 4.3 to validate the latest commits.
Please see #222

**Pull request merged**
