### PR TITLE
added mp3-channel endpoint

### PR DESCRIPTION
**Pull request by comcloudway**
NOTICE: Redo of #738 (had to use a patchfile to transfer the commits as trying to merge the file from master to next failed and I hat to re-fork the repo - the old PR still holds the separate Commits)

Basically this allows better m3u playlist support, because the audio player can now automatically request a channel change before connecting to the audio stream.

This can be accessed at `/mp3-channel/<channel>/<program>`, this way the `/mp3/<program>` endpoint stays the same.
Basically requesting `/mp3-channel/` is the same as sending a POST request to `/channel`, waiting for the sync to finish and then requesting `/mp3/`.
But as simple audio players like kodi or vlc can not do that when playing back a `.m3u` file this new endpoint enables them to do this as one request.

This would allow the end user to have multiple different radio programs on different channels in the same playlist, e.g. (a couple of somewhat local radio stations)
```m3u
#EXTM3U
#EXTINF:0,SAW
#EXTVLCOPT:network-caching=500
http://127.0.0.1:8080/mp3-channel/11C/0xd5d9
#EXTINF:0,MDR AKTUELL
#EXTVLCOPT:network-caching=500
http://127.0.0.1:8080/mp3-channel/6B/0xd3d5
```

Inside of kodi this would allow the user to choose between multiple different radio stations without the need to restart welle-cli or perform multiple network requests

### CODE REVIEW

**Review by mpbraendli — APPROVED** [review]

**Comment by mpbraendli** [comment]
Thanks for the implementation of this feature!

**Comment by comcloudway** [comment]
I just read through the issue mentioned above and noticed that I never came across the forum-post mentioned in #741 .
This is why implementation does not work exactly the same as the one proposed on the forum:
From what I can tell both should achieve the same result though, but the forum proposed a solution based on sleeping, which does not work reliably on devices like a raspberry pi as he takes longer to scan (as far as I know).

I just wanted to clarify that this implementation exposes another endpoint at `/mp3-channel/<channel>/<program>`

**Comment by comcloudway** [comment]
@mpbraendli I believe that my implementation might be faulty, as the while loop also pauses the /mp3 request. 
This means that when the user forgot to tune before requesting /mp3 the while loop wont ever exit (which would keep the user from seeing an error screen and at some point the request  would timeout)

Should I do a second PR to address the issue? I believe that wrapping send_mp3 in a second function which does the waiting should solve the problem

**Comment by mpbraendli** [comment]
Either open a new PR, or ask @AlbrechtL to give you push rights to the 'next' branch. I'd be happy to review commits in both cases.

**Comment by comcloudway** [comment]
Got a PR ready (#472) but I haven't had time to test it (my antenna has been mounted now and I don't really have access to it)

**Pull request merged**
