### PR TITLE
Add LimeSDR support through SoapySDR

### PR DESCRIPTION
**Pull request by mpbraendli**
Hi Albrecht,
the automatic gain setting doesn't work immediately, you have to disable and enable it when you switch frequency, I'm not sure why.
Please tell me if you see other necessary improvements for that.
cheers
mpb

### CODE REVIEW

**Comment by mpbraendli** [comment]
SoapySDR could be used with other devices too (e.g. HackRF) but the antenna setting is hard-coded for the LimeSDR Antenna port 1 with wide-band matching.
Adding a command line or GUI option to choose the antenna would make it compatible with other SoapySDR-supported devices.

**Comment by AlbrechtL** [comment]
Thanks for the contribution.

1. Is there a special need that you need `#include "CSoapySdr.h" `inside main.cpp? Because if you don't want to compile the soapysdr input the compiler fails on this line. I removed it.
2. Can you write a manual page for the welle.io website? You find the website repository [here](https://github.com/AlbrechtL/albrechtl.github.io). The rtl-sdr page for example is [here](https://github.com/AlbrechtL/albrechtl.github.io/blob/master/pages/rtl_sdr.md).
3. If you want that the Windows version includes the SoapySDR input, add all necessary file to https://github.com/AlbrechtL/welle.io-win-libs, please.

**Comment by mpbraendli** [comment]
1. Not until we want to make the antenna selection configurable.
2. I will do!
3. I'm afraid I have no way to test a windows build. It would make sense because SoapySDR supports Windows too.

**Comment by mpbraendli** [comment]
2. What do you think about this draft? https://gist.github.com/mpbraendli/215ecd538ad003a85446c6fe80e3a12f

**Comment by AlbrechtL** [comment]
Perfect. I updated the website.

**Pull request merged**
