### PR TITLE
Another approach to the index.html and index.js

### PR DESCRIPTION
**Pull request by fridrich**
This commit is basically compiling the index.html and index.js as resources into the binary. It avoids one to have to install them and bother about finding where they are.

### CODE REVIEW

**Comment by fridrich** [comment]
Now, this would need the xxd resource compiler, but I find that the advantage of having a single binary is great

**Comment by mpbraendli** [comment]
Hi, I like the idea, even though for development it means changing the HTML incurrs a compile/link cycle, and it makes user-customisation more difficult. But it avoids file availability issues.

Why did you move from C++17 to C++14?

Using `xxd -i` is cool, I was wondering if we could use `od` instead, because that's in coreutils, but it'd need more tinkering. So I'm ok with adding `xxd` as a build-time dependency.

**Comment by fridrich** [comment]
I moved the C++17 back to the C++14 because originally in the reverted commit I added it only to be able to use std::filesystem::path which is now not needed again. That is why I also restored lower cmake requirement

**Comment by fridrich** [comment]
Ping?

**Comment by mpbraendli** [comment]
Thanks for the reminder!

**Pull request merged**
