### PR TITLE
macOS DMG image build

### LINKED ISSUE #442: [macOS] Create DMG image
welle.io runs also on macOS but it is not easy to compile and install it specifically for non experts.

It would be really nice to have a DMG to run welle.io.
Qt has also a deploy tool for macOS (https://doc.qt.io/archives/qt-5.11/osx-deployment.html).

The Linux AppImage is build with Travis CI. Luckily Travis support also macOS (https://docs.travis-ci.com/user/reference/osx/). So it is possible to create the DMG automatically like the Windows installer and the Linux AppImage.

@tenzap Are you interested in creating a DMG image?

### PR DESCRIPTION
**Pull request by orryverducci**
This pull request adds a macOS build to Travis CI, which creates a DMG image for easy deployment and installation. This resolves #442.

Due to the licensing concerns raised in the issue this builds both the GUI and CLI, but packages and deploys only the GUI.

This also corrects a couple other minor issues with the Travis builds:

- Removes the deprecated sudo tag
- Fixes the CLI CMake build to build only the CLI, previously this was running a duplicate build of the GUI as well as the CLI

Bintray deployment has not been tested but I think it should work. Let me know if it doesn't.

### CODE REVIEW

**Comment by tenzap** [comment]
Cool. Does the resulting DMG & work on all osx versions >= 10.11 ?

**Comment by orryverducci** [comment]
As it's built using Qt 15.4 I believe only macOS >= 10.13 is supported.

So far I've only tested it on my Mac running 10.15 (Catalina). It should work on older versions, but I'll spin up a 10.13 VM to double check.

**Comment by AlbrechtL** [comment]
The build was successful.
https://travis-ci.org/github/AlbrechtL/welle.io/jobs/692730530

But the resulting DMG has thw wrong file name format.
https://bintray.com/package/files/albrechtl/welle.io/welle.io_nightly?order=asc&sort=name&basePath=build%2Fsrc%2Fwelle-gui&tab=files

Please use a filename format similar to e.g. Linux "20200529_e9f923b_Linux_welle-io-x86_64.AppImage". It is `<build date>_<git hash>_<OS>_welle-io.<extension>`

**Comment by orryverducci** [comment]
Thanks @AlbrechtL!

As for the filename, the build script does rename the DMG to the correct format, so the Bintray deployment must be picking up the wrong file.

I'll have another look at it.

**Pull request merged**
