### PR TITLE
Updated norwegian bokmål

### PR DESCRIPTION
**Pull request by FartherOut**
Updated and tested the translations.

### CODE REVIEW

**Comment by AlbrechtL** [comment]
Thanks for the translation.

Please add Norwegian also to the settings drop down menu, see here https://github.com/AlbrechtL/welle.io/issues/341#issuecomment-528973521.

**Comment by FartherOut** [comment]
Thy will be done

**Comment by AlbrechtL** [comment]
Thanks for responding so fast. Did you test the language menu?

**Comment by FartherOut** [comment]
Indeed I did.

**Comment by AlbrechtL** [comment]
Well done, good job!

**Pull request merged**
