### PR TITLE
welle-io: don't store label of gain value in settings, store only the value

### PR DESCRIPTION
**Pull request by tenzap**

### CODE REVIEW

**Comment by AlbrechtL** [comment]
Did you test what happens if a user is coming with an existing config file?

**Comment by tenzap** [comment]
Yes, it is ok, because the value will be updated with the one in another setting, that is really the one used to restore the gain

**Comment by AlbrechtL** [comment]
OK, but I don't see the advanced of using two text items instead of just one.

**Comment by tenzap** [comment]
It is just that before the value stored also the label which changes depending on the language and it was confusing when reading welle.io.conf (especially when working on the translation feature) I didn't understand at first that the important setting is "manualGainState" and not the "manualGainValue"

**Pull request merged**
