### PR TITLE
update nl_NL translations

### PR DESCRIPTION
**Pull request by meeuw**
update nl_NL translations

### CODE REVIEW

**Comment by AlbrechtL** [comment]
Please provide also the QM file.

**Comment by AlbrechtL** [comment]
Thanks for the update.

Unfortunately the TS file has some conflicts now. Please resolve these conflicts and provide the QM file as well.

**Comment by meeuw** [comment]
Could you please explain why the QM file is required? When I use cmake to build welle.io it's automatically created...

**Comment by AlbrechtL** [comment]
> When I use cmake to build welle.io it's automatically created...

Mhh, I only use qmake. In this case to QM file is not automatically created.

**Comment by meeuw** [comment]
allright, done!

**Pull request merged**
