### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by dforsi**

### CODE REVIEW

**Review by AlbrechtL — CHANGES_REQUESTED** [review]
Please change to next branch instead of the master branch, please.

**Comment by dforsi** [comment]
I changed the branch.
Maybe you could add a pull request template, even a very simple one saying which branch to use.

https://docs.github.com/en/articles/creating-a-pull-request-template-for-your-repository

Here is a project with a verbose template which I found easy to fill
https://github.com/OctoPrint/OctoPrint/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by dforsi** [comment]
FYI, I don't need this patch when building for Qt6

**Review by AlbrechtL — APPROVED** [review]

**Comment by AlbrechtL** [comment]
> Maybe you could add a pull request template, even a very simple one saying which branch to use.

Thanks for this idea! I you like you can send a PR for the `PULL_REQUEST_TEMPLATE.md`. Just put `PULL_REQUEST_TEMPLATE.md` in the root directory of this repo.

**Pull request merged**
