### PR TITLE
gui: new feature: add play/stop button

### PR DESCRIPTION
**Pull request by tenzap**
Screenshot_20210222_092147

It will play the last played station, if there isn't any, a message is displayed telling to select a station.

Start/Stop button is placed in the top bar (see PR #532)
When mouse is hovered over play/stop icon, a small tool tip is displayed

There is a little "play" icon next to the name of the station in the stations list so that one knows which station is currently playing

### CODE REVIEW

**Review by AlbrechtL — APPROVED** [review]

**Comment by AlbrechtL** [comment]
Thanks!
I will merge it now. Please be prepared if I have small change request after I did some tests.

**Comment by AlbrechtL** [comment]
I have first test results
- The antenna symbol is not working anymore
- With which inputs did your test the code? Definitely with rtl-tcp stopping is working but not replaying.

**Comment by tenzap** [comment]
- There is a fix for antenna symbol in the part4 (needing part3 merged first = PR #628) (or you can also look in the 4th commit or the old PR #532
- I tested it with rtl-sdr (and probably soapy last year)

**Comment by AlbrechtL** [comment]
> I tested it with rtl-sdr (and probably soapy last year)

Please test it also with rtl_tcp.

**Comment by tenzap** [comment]
It is very likely it is due to the backend

**Comment by AlbrechtL** [comment]
OK. I merged https://github.com/AlbrechtL/welle.io/pull/628. Can you provide a fix for antenna symbol please?

**Pull request merged**
