### PR TITLE
Added again DESTDIR in pro-file

### PR DESCRIPTION
**Pull request by andimik**

### CODE REVIEW

**Comment by AlbrechtL** [comment]
Why you need the DESTDIR, exactly?

**Comment by andimik** [comment]
It was in there for a very long time ;-)

**Comment by andimik** [comment]
Albrecht should decide...

**Comment by AlbrechtL** [comment]
I don't see a real enhancement by adding a DESTDIR.

**Comment by andimik** [comment]
You've misunderstood me. I was closing that PR ;-)

**Pull request closed without merging**
