### PR TITLE
gui: new feature: add play/stop button + Volume slider + hotkeys

### PR DESCRIPTION
**Pull request by tenzap**
It will play the last played station, if there isn't any, a message is displayed telling to select a station.

welle-playStop1
welle-playStop2

Also add Volume Slider (can be toggled by clicking the speaker icon or auto-hides after 5sec)
welle-Volume

### CODE REVIEW

**Comment by andimik** [comment]
Cool, I am using this file as well... :smile:

**Comment by tenzap** [comment]
This PR reveals this:
- When clicking "stop" (which calls CRadioController::stop() ) CPU usage goes down from ~35% to 5% with RTLSDR & Raw file, but with SoapySDR it goes down to  ~0% (I didn't test the other devices). 
- So I guess, something is not being stopped in some cases.
- I noticed that with SoapySDR there is this line in the log `OFDM-processor: input not ok, closing down` which seems to mean it stops the OFDM-processor
- So I tried to add ```radioReceiver->stop();``` to `CRadioController::stop()` https://github.com/AlbrechtL/welle.io/blob/8fc57390bfb1f312094425a329ff52635b405c17/src/welle-gui/radio_controller.cpp#L234 and this actually brings CPU usage to ~0% for RTLSDR & RawFile.

But I don't know whether 
- this is the good thing to do
- other things have to be added (any other check, things to do...), any side effects ?
- where exactly to add this call inside `CRadioController::stop()`

@mpbraendli what is you opinion on this, what do you suggest ?

**Comment by tenzap** [comment]
Add hotkey / keyboard shortcuts support:

- F1..F12 | 1..9: Play the station n° x in the stations list
- Space | Media Play, stop, pause, play/pause: Play/Stop
- n | Media next: play next station in list
- p | Media Previous: play previous station
- m | Volume Mute: mute/unmute
- Ctrl+Up | Volume Up: Volume Up
- Ctrl+Down | Volume Down: Down

**Comment by tenzap** [comment]
Is there anything blocking here ? My [comment](https://github.com/AlbrechtL/welle.io/pull/532#issuecomment-606460067) is actually not an issue anymore with the latest push (Apr/27) on this PR

**Review by AlbrechtL — CHANGES_REQUESTED** [review]
Thanks for your contributions!
Please split your patch into multiple PRs. Per feature one PR.

**Comment by AlbrechtL** [comment]
Regarding the audio features:
1. I would prefer to put the loudspeaker icon into the top bar (with "welle.io")
2. When the user clicks or touches the loudspeaker icon a popup is showing with the volume slider and a mute option.
3. The stop button can be also placed inside top bar.

Can you try these?

**Comment by tenzap** [comment]
Why split 1 PR with 3 commits (each being a feature) into 3 PR each with one commit ? I don't see the point. In the end it will look the same in the branch.

Concerning the other 3 points, may I suggest merging first the way I made it and then create a change request with the updates in case someone wants to work on adapting the GUI to your wishes ?

It seems this feature is expected.

**Comment by AlbrechtL** [comment]
I would like to keep the UI as simple as possible and to avoid to many buttons. For that reason I suggest the changes. If you want to have your changes in welle.io please follow my suggestion.

Please create a PR one by one otherwise I have issues to review the code changes.

**Comment by tenzap** [comment]
I can't have a look at this anymore, sorry. Anyone willing to do the changes is welcome.

**Pull request closed without merging**
