### PR TITLE
fix loading & update of soapySDR params

### PR DESCRIPTION
**Pull request by tenzap**
I had to duplicate the CDeviceID Class, I couldn't find how to do without.

### CODE REVIEW

**Comment by tenzap** [comment]
Can I have your advice on my first comment of this PR ? Is the duplication ok ?

**Comment by mpbraendli** [comment]
I don't understand why the backend needs to store the input device params. This information should come from the frontend directly (similar to the gain settings, AirSPY bias tee, or SoapySDR antenna. That would make the duplication unnecessary.

Is there a reason why that doesn't work?

**Comment by tenzap** [comment]
Have you had a look at #423 ? Maybe that does answer your question ?
It is necessary to initialise the arguments of soapysdr with version 0.6 otherwise it uses "audio" device instead of the usb dongle...

**Comment by tenzap** [comment]
I don't understand what you mean. The soapysdr backend needs to be initialised. The only way I found was to send the init arguments via the constructor.
If you have a better implementation please do.

**Comment by tenzap** [comment]
Maybe the difference with other intput devices is that the params for the other input devices are not needed to initialize the device. They can be set afterwards as a modification. But with soapy, the driver needs to be set first from what I can remember and has to be in the constructor, otherwise there may be segfaults in numerous other calls because many things are not well initialized. Or something like that...

**Comment by AlbrechtL** [comment]
From what I understood is that, you are doing these changes to support Soapy 0.6 and below. 

Could it be an option to support only Soapy 0.7 and greater?
I mean at one place the Distros will update to 0.7 anyway. At the moment the Soapy interface is only used by experts which are able to compile welle.io. In this case they can also compile Soapy 0.7 like you did.

**Comment by tenzap** [comment]
As I already said, debian stable & testing ships with 0.6. Stable will not change for probably 2-3 yeas. That's a long time...
Why not support 0.6 if there is this fix ? Any problem with it ?
Moreover, this not only fixes that but also a few other bugs. Soapy was very buggy... The params from the gui were not taken into account.
Why reserve soapy support to only experts who are able to compile welle.io  ? Maybe they also would like to have something that simply works and doesn't need to be digged into and fixed individually by each dev...

I tested this PR thouroughly and it does work and couldn't find any bug. Moreover merging this into dev is probably the right place to have that confirmed by others.

Again there are issues also with soapy 0.7 that this PR fixes, I just mentionned only 0.6 because it was the most visible one leaving it really completely unusable and buggy.

**Comment by tenzap** [comment]
Finally with 0.7 it will just hide the bugs of welle.io because it seems to work only because Soapy by chance with 0.7 initializes the device in a way that it does work.
However imagine the case where someone has 2 RF devices managed by soapy, then initializing the device arguements correctly in welle.io will be necessary, and this is right now completely buggy and ineffective in welle 2.0, wether one uses 0.6 or 0.7.
Now Imagine the case where one wants to add additional parameters to the soapy driver initialization, then you will have the same problem that the parameters set in welle.io will not be taken into account.
Currently updating the parameters in the GUI and clicking "apply" also doesn't work.
So according to me this has to be fixed, and this PR fixes all that.
Hopefully you will understand and accept that PR.
It is just by chance that it works with 0.7, but doesn't fix anything on welle side, even with 0.7

**Comment by mpbraendli** [comment]
> I don't understand what you mean. The soapysdr backend needs to be initialised. The only way I found was to send the init arguments via the constructor.

It should be possible to postpone it until we know the driver arguments, I'll try that out.

**Comment by mpbraendli** [comment]
I've tried a different approach in bb7ed38
- `CSoapySdr` only initialises when the driver arguments are set
- `CRadioController` caches the settings in a map

There are probably unhandled edge cases. What do you think?

**Comment by tenzap** [comment]
I just tried "next" including bb7ed38 . I change from rtl-sdr to soapySDR in the gui, and immediately have segfault :/

**Comment by tenzap** [comment]
Provided you agree, replacing the condition bellow seems to do the trick
https://github.com/AlbrechtL/welle.io/blob/bb7ed381e8f532d3956cdab236e58d4f6d62cdc1/src/input/soapy_sdr.cpp#L231


replace 
```
if (m_driver_args != args) {
```
by
```
if (!m_running || m_driver_args != args) {
```

**Comment by mpbraendli** [comment]
Thanks for testing this. I've added a check in `getDescription()` (commit 74be202) because deferencing a pointer that might be null is always wrong.

**Comment by tenzap** [comment]
Adding this piece of code here (in the `if(device)` after the `device->setDeviceParam(dp, v);` call
https://github.com/AlbrechtL/welle.io/blob/4b9ab6d00046927309c84ea4aa31df679ce40c59/src/welle-gui/radio_controller.cpp#L207 
fixes both issues 
```
        if (dp == DeviceParam::SoapySDRDriverArgs)
            openDevice(CDeviceID::SOAPYSDR,1);
```

**Comment by AlbrechtL** [comment]
@tenzap, @mpbraendli Any update here?

**Comment by tenzap** [comment]
Another bug in addition to those 2 above  (https://github.com/AlbrechtL/welle.io/pull/428#issuecomment-547517594) : 
* I also noticed when using SoapySDR with "uninitialised" (test it with an invalid device parameter) then there is a crash when enabling/disabling coarse correction, in the expert setting.

```
Thread 1 (Thread 0x7f632b6eec40 (LWP 31420)):
[KCrash Handler]
#6  0x00007f632faa67bb in raise () from /lib/x86_64-linux-gnu/libc.so.6
#7  0x00007f632fa91535 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#8  0x00007f632fe5b983 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007f632fe618c6 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007f632fe61901 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x000055a1d7456e37 in std::thread::operator= (__t=..., this=0x55a1d97b88a0) at /usr/include/c++/8/thread:153
#12 OFDMProcessor::start (this=0x55a1d97b88a0) at /build/welle.io-next/src/backend/ofdm-processor.cpp:127
#13 0x000055a1d745e357 in RadioReceiver::setReceiverOptions (this=0x55a1d97b8120, rro=...) at /build/welle.io-next/src/backend/radio-receiver.cpp:110
#14 0x000055a1d74300a8 in CRadioController::disableCoarseCorrector (this=<optimized out>, disable=<optimized out>) at /build/welle.io-next/src/welle-gui/radio_controller.cpp:426
#15 0x000055a1d747602b in CRadioController::qt_static_metacall (_o=0x7ffe80f59140, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>) at /build/welle.io-next/build/welle-io_autogen/MOX6SOXE6H/moc_radio_controller.cpp:508
#16 0x000055a1d747759b in CRadioController::qt_metacall (this=0x7ffe80f59140, _c=QMetaObject::InvokeMetaMethod, _id=63, _a=0x7ffe80f560d0) at /build/welle.io-next/build/welle-io_autogen/MOX6SOXE6H/moc_radio_controller.cpp:1087
#17 0x00007f6330ddcb8d in ?? () from /lib/x86_64-linux-gnu/libQt5Qml.so.5
#18 0x00007f6330d44421 in ?? () from /lib/x86_64-linux-gnu/libQt5Qml.so.5
#19 0x00007f6330d45855 in ?? () from /lib/x86_64-linux-gnu/libQt5Qml.so.5
#20 0x00007f6330d465a2 in QV4::QObjectMethod::callInternal(QV4::Value const*, QV4::Value const*, int) const () from /lib/x86_64-linux-gnu/libQt5Qml.so.5
#21 0x00007f6330d60a69 in QV4::Runtime::method_callProperty(QV4::ExecutionEngine*, QV4::Value*, int, QV4::Value*, int) () from /lib/x86_64-linux-gnu/libQt5Qml.so.5
#22 0x00007f6330d541f2 in ?? () from /lib/x86_64-linux-gnu/libQt5Qml.so.5
#23 0x00007f6330e0a4ff in QQmlJavaScriptExpression::evaluate(QV4::CallData*, bool*) () from /lib/x86_64-linux-gnu/libQt5Qml.so.5
#24 0x00007f6330d9e527 in QQmlBoundSignalExpression::evaluate(void**) () from /lib/x86_64-linux-gnu/libQt5Qml.so.5
#25 0x00007f6330d9f6bb in ?? () from /lib/x86_64-linux-gnu/libQt5Qml.so.5
#26 0x00007f6330de75f3 in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /lib/x86_64-linux-gnu/libQt5Qml.so.5
#27 0x00007f6330d81a8a in QQmlData::signalEmitted(QAbstractDeclarativeData*, QObject*, int, void**) () from /lib/x86_64-linux-gnu/libQt5Qml.so.5
#28 0x00007f63301e619f in QMetaObject::activate(QObject*, int, int, void**) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#29 0x00007f632f736788 in QQuickAbstractButton::setChecked(bool) () from /lib/x86_64-linux-gnu/libQt5QuickTemplates2.so.5
#30 0x00007f632f736dbf in QQuickAbstractButtonPrivate::toggle(bool) () from /lib/x86_64-linux-gnu/libQt5QuickTemplates2.so.5
#31 0x00007f632f742c75 in QQuickCheckBox::nextCheckState() () from /lib/x86_64-linux-gnu/libQt5QuickTemplates2.so.5
#32 0x00007f632f738caa in QQuickAbstractButtonPrivate::handleRelease(QPointF const&) () from /lib/x86_64-linux-gnu/libQt5QuickTemplates2.so.5
#33 0x00007f632f74fcd5 in QQuickControl::mouseReleaseEvent(QMouseEvent*) () from /lib/x86_64-linux-gnu/libQt5QuickTemplates2.so.5
#34 0x00007f6331170eb8 in QQuickItem::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Quick.so.5
#35 0x00007f633155b4c1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#36 0x00007f6331562970 in QApplication::notify(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#37 0x00007f63301bd4f9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#38 0x00007f633118925b in QQuickWindowPrivate::deliverMouseEvent(QQuickPointerMouseEvent*) () from /lib/x86_64-linux-gnu/libQt5Quick.so.5
#39 0x00007f6331189d3b in QQuickWindowPrivate::deliverPointerEvent(QQuickPointerEvent*) () from /lib/x86_64-linux-gnu/libQt5Quick.so.5
#40 0x00007f633118a66f in QQuickWindowPrivate::handleMouseEvent(QMouseEvent*) () from /lib/x86_64-linux-gnu/libQt5Quick.so.5
#41 0x00007f6330575205 in QWindow::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#42 0x00007f633118c2db in QQuickWindow::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Quick.so.5
#43 0x00007f633155b4c1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#44 0x00007f6331562970 in QApplication::notify(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#45 0x00007f63301bd4f9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#46 0x00007f6330568ff3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#47 0x00007f633056ae75 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#48 0x00007f633054506b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#49 0x00007f632b32140b in ?? () from /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#50 0x00007f63301bc1cb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#51 0x00007f63301c41a2 in QCoreApplication::exec() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#52 0x000055a1d741b71d in main (argc=<optimized out>, argv=<optimized out>) at /build/welle.io-next/src/welle-gui/main.cpp:171
[Inferior 1 (process 31420) detached]
```

**Comment by AlbrechtL** [comment]
What is the current state here?
Depends  https://github.com/AlbrechtL/welle.io/pull/481 on this PR?

**Comment by tenzap** [comment]
#481 fixes https://github.com/AlbrechtL/welle.io/pull/428#issuecomment-547517594
While https://github.com/AlbrechtL/welle.io/pull/428#issuecomment-554307985 is still present.
For me, this PR can be closed once #481 is merged and https://github.com/AlbrechtL/welle.io/pull/428#issuecomment-554307985 is fixed (if mpbraendli is ok)

**Comment by mpbraendli** [comment]
I agree that the second issue still needs to be fixed. I pushed commit 544a1b3 in the hope that fixes it, can you take those changes into your pull request (either manually or with `git cherry-pick`) and try them out?

**Comment by tenzap** [comment]
I'm not sure to understand what you mean. You almost already rewrote/reintegrated and committed all that is in this PR in the next/master branches. I already had a look at the difference between your implementation and this PR and it is almost equivalent though implemented a bit differently.
It would be too much effort for no gain to still modify this PR now since it doesn't really bring anything else.
I think that once #481 is merged and if your commit 544a1b3 fixes the last issue, then the best would be to simply close the PR. I'll give a test at your commit as soon as I can.

**Comment by mpbraendli** [comment]
Ah yes, I thought the PR was still to be merged, my mistake.

I'm sorry this topic went back and forth a bit, but I appreciate your efforts in addressing the problem, both with the initial changes in the PR and with the testing you did afterwards. Thank you for this.

I'll close this PR and open an issue for tracking the segmentation fault.

**Pull request closed without merging**
