### PR TITLE
Drop extra semi-colons (chunk 2)

### PR DESCRIPTION
**Pull request by gvanem**
From my:<br>
*   **head-fork:master** to **base: master**

It should have been:<br>
*  **head-fork:next** to **base: next**

But I'm still a a Git *n00b*.

### CODE REVIEW

**Comment by gvanem** [comment]
It's from **head-fork:master** to  **base: next** now. Okay?

**Comment by mpbraendli** [comment]
@basicmaster can you have a look at commit 5ef456373 ? Some of the changes there touch your PAD decoder code.
I'll apply the correction, but without the brace style change, because we want to keep this code as close as possible to @basicmaster's code.

**Comment by mpbraendli** [comment]
Your patch doesn't apply to `next` without conflicts, so I'll do this manually. I also found a few other instances of trailing semicolons.
See commit 7900bd1

**Comment by basicmaster** [comment]
@mpbraendli 
Thanks for letting me know. I removed all superfluous trailing semicolons (https://github.com/Opendigitalradio/dablin/commit/3ca7cbfa4e05cf349daefcf4b1b83d84e25d2462) and adopted your idea to move the PAD len error handling to the decoder observer interface (https://github.com/Opendigitalradio/dablin/commit/0c0e2d62e9de04d6bc36fe7e6dfa636daeb02e6d).

**Comment by AlbrechtL** [comment]
The task to update the PAD code is still open (https://github.com/AlbrechtL/welle.io/issues/223). When I update it than all changes will be included.

**Pull request closed without merging**
