### PR TITLE
3d view integration

### PR DESCRIPTION
**Pull request by viktorgino**

### CODE REVIEW

**Comment by viktorgino** [comment]
The station browser work either by using mouse scroll or click and drag. Also works on touch screen by dragging left & right. Might need to tweak the sensitivity of the dragging or add an step size option.

**Comment by AlbrechtL** [comment]
Thank you very much for the pull request.

As I understood your code, you replaced the landscape view totally with the 3D view. For now I think it is better to keep both modes landscape view and 3D view and make it changeable in some way.

**Comment by viktorgino** [comment]
Okay, shouldn't be too hard to add a 2D/3D flip button. I'll add it in the next couple of days.

**Comment by AlbrechtL** [comment]
Great idea with the switch!
I close this pull request for the moment. Please open a new one if you added the switch.

**Pull request closed without merging**
