### PR TITLE
Updated the EBU Latin charset to ETSI TS 101 756 V1.8.1 from V1.6.1

### PR DESCRIPTION
**Pull request by sheimers**
This should fix issue #283 that I opened some days ago. The new character table comes from ODR-PadEnc and has been automatically converted from UTF8 to UCS2.

The following code has been used for the conversion:
```
int main(){
  std::wstring_convert<std::codecvt_utf8<char16_t>, char16_t> ucs2conv;
  std::cout << "/* 0x00 - 0x07 */   0x00, ";
  std::cout << std::setbase(16) << std::setfill(' ');
  for (int i=0;i<CHARSET_TABLE_ENTRIES;i++){
    std::u16string ucs2 = ucs2conv.from_bytes(utf8_encoded_EBU_Latin[i]);
    std::cout << std::showbase << std::setw(6) << ucs2[0];
    if ((i+2) % 8) {
      std::cout << ", ";
    }
    else{
      if (i == (CHARSET_TABLE_ENTRIES - 1)) std::cout << "\n";
      else {
        std::cout <<  ",\n/* "    << std::setw(4) << i+2 << " - " << std::setw(4) <<  i + 1 + 8 <<  " */ ";
      }
    }
  }
}
̋```

### CODE REVIEW

**Comment by mpbraendli** [comment]
I quickly checked, it's the same table as in the latest spec version: TS 101 756 v2.1.1 https://www.worlddab.org/technology-rollout/standards/technical-specifications-list

Could we put you conversion code somewhere inside an `#ifdef`? Otherwise we'll forget about it.

**Comment by sheimers** [comment]
Yes sure, you can do whatever you want with this code. But #ifdef seems weird. It's not meant to be used at runtime. So I recommend either to add it inside a comment section with a hint that it needs the table from ODR-PadEnc/src/charset.cpp or maybe create a seperate source file which #includes ../../ODR-PadEnc/src/charset.cpp and creates a binary that prints out the converted table to stdout that can then be copied to the welle.io source code or anywhere else where it is useful in UCS2.

**Comment by AlbrechtL** [comment]
I find the idea great to put the conversation code into a comment.

@sheimers Please update your pull request with your conversation code inside a comment.

**Comment by sheimers** [comment]
OK, I have included the source code in the updated pull request. Unfortunately I had to use ugly single line comments. Using a comment block with /* and */ did not work because there are some of these already in the source code that should go into the new character table. If someone knows a nicer option for making a comment block containing other comments please let me know.

**Comment by mpbraendli** [comment]
I might suggest an `#ifdef` but that feels a bit like a déjà-vu... :-)

**Comment by sheimers** [comment]
Ok, now I understand why you suggested the #ifdef. It still looks strange to me, but it's now easy to copy&paste to an empty file an compile there. It does not work if you #define ODRTABLE in the original file, compiling fails because of the two main functions.

**Comment by AlbrechtL** [comment]
@mpbraendli Why do you prefer an ifdef instead of single line comments? From my point of view is the usage of single line comments much more transparent then to use ifdefs. Especiall, in this case is the code broken if somebody defines ODRTABLE.

**Comment by sheimers** [comment]
It actually does compile if done manually with the correct options:

`heimers@foehr:/tmp/welle.io/src/backend$ g++ -fPIC -DODRTABLE  -I  /usr/include/x86_64-linux-gnu/qt5/  -I /usr/include/x86_64-linux-gnu/qt5/QtCore/ -lQt5Core -o chartable charsets.cpp
`

**Comment by AlbrechtL** [comment]
I totally overlooked that you patched the master branch. But the current development is done in the next branch.
Please simply open a new pull request for the next branch with your changes.

**Comment by mpbraendli** [comment]
@AlbrechtL you're better off merging `master` into `next` or cherry-picking the four commits manually. Opening a new pull request for this is just overhead.

I can do it if you want.

**Comment by AlbrechtL** [comment]
I understand your point. But for me it is easier to tell contributors to open a new pull request than I do things manually. In the end I just want to push the merge button. :-)

**Pull request merged**
