### PR TITLE
Fix Mac Travis Build

### LINKED ISSUE #697: [macOS] Travis build failed - again
The travis macOS build is broken again. See here: https://app.travis-ci.com/github/AlbrechtL/welle.io/jobs/553714872#L2578

@orryverducci Can you have a look, please?

### PR DESCRIPTION
**Pull request by orryverducci**
Migrates the Mac Travis build to macOS Monterey (12.1) and Xcode 13.2. Fixes #697.

~~**NOTE:** The Linux build currently fails as Flatpak is waiting for user confirmation. I've left this to you @AlbrechtL as you're more familiar with the Linux build than I am.~~

### CODE REVIEW

**Comment by orryverducci** [comment]
Just realised I based this on the master branch, not the next branch, so the build on this repo still fails as it's trying to do an Android build that fails. I've switched this to draft while I fix it.

Ignore my comment about the Linux build failing, that's obviously been fixed since.

**Review by AlbrechtL — APPROVED** [review]
Thanks! I will take a look why macOS wants to do the Android build.

**Comment by orryverducci** [comment]
All fixed, the issue was indeed the code in the script used by both Linux and Mac.

I've move the Android build in to its own job with its own script, and I also gave it a bit of a clean up while I was there.

I've also added a workaround to the Mac build to prevent Homebrew updating a dependency (Ansible) which can break the Travis VM.

**Review by AlbrechtL — APPROVED** [review]

**Comment by AlbrechtL** [comment]
Cool. Thanks!

**Pull request merged**
