### PR TITLE
Continuous builds for Linux

### PR DESCRIPTION
**Pull request by probonopd**
This PR, when merged, will compile this application on [Travis CI](https://travis-ci.org/) upon each `git push`, and upload an [AppImage](http://appimage.org/) to a temporary download URL on transfer.sh (available for 14 days). The download URL is toward the end of each Travis CI build log of each build (see below for how to set up automatic uploading to your GitHub Releases page).

For this to work, you need to enable Travis CI for your repository as [described here](https://travis-ci.org/getting_started) __prior to merging this__, if you haven't already done so.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Works for most Linux distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Just one format for all major distributions
- Works out of the box, no installation of runtimes needed (unlike Snap and Flatpak)
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs (unlike Flatpak)
- Can use the same AppImages when dual-booting multiple distributions

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

__Please note:__ Instead of storing AppImage builds temporarily for 14 days each on transfer.sh, you could use GitHub Releases to store the binaries permanently. This way, they would be visible on the Releases page of your project. This is what I recommend. See https://docs.travis-ci.com/user/deployment/releases/. If you want to do this for continuous builds, also see https://github.com/probonopd/uploadtool.

If you would like to see only one entry for the Pull Request in your project's history, then please enable [this GitHub functionality](https://help.github.com/articles/configuring-commit-squashing-for-pull-requests/) on your repo. It allows you to squash (combine) the commits when merging.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

### CODE REVIEW

**Comment by probonopd** [comment]
A solution for automatically unloading the kernel module and for installing an udev rule still needs to be implemented, similar to the discussion [here](https://github.com/JvanKatwijk/qt-dab/issues/34#issuecomment-289270761).

**Comment by AlbrechtL** [comment]
Great idea to use Travis! Many thanks to you! Lets see how its performs.

**Comment by probonopd** [comment]
Looks like Travis CI has an issue right now, hopefully resolved soon:
https://www.traviscistatus.com/incidents/93wfcv0ksqrz

**Comment by AlbrechtL** [comment]
It is possible to switch to QT 5.7 or QT 5.9 beta inside the AppImage? Unfortunately QT 5.8 has a bug #35.

**Comment by probonopd** [comment]
Sure that is doable once Qt 5.9 appears in the beineri ppa, or someone writes a script to identify and download the needed components from https://download.qt.io/development_releases/qt/5.9/5.9.0-alpha/submodules/.

**Comment by AlbrechtL** [comment]
OK, I downgraded travis.yml to QT 5.7. Once QT 5.9 is available we can update it again.

**Comment by probonopd** [comment]
Seems to have worked:
https://transfer.sh/aQcEq/welle_io-git.3dde3a0-x86_64.AppImage

**Comment by AlbrechtL** [comment]
It seems that in leatest builds something is going wrong.
Compilation is OK but `linuxdeployqt `reports `ERROR: ldd outputLine: "libpulsecommon-4.0.so => not found"` and no AppImage is created.
Can you check this problem please?

**Comment by probonopd** [comment]
Opened https://github.com/AlbrechtL/welle.io/pull/53 which should address that.

**Pull request merged**
