### PR TITLE
Replace the window title by the stationName 

### PR DESCRIPTION
**Pull request by tenzap**
therefore one known which station is playing in the taskbar without opening the window

### CODE REVIEW

**Comment by AlbrechtL** [comment]
I don't know if replacing the window title by the current station is a good idea. Could it be an option the put the current station information to the welle.io system tray?

**Comment by tenzap** [comment]
Most apps have a window title reflecting the current situation of the app. (the current folder on file managers, the current page title for web browsers). IMO having to move the mouse over the sys tray is one action too much to get the info of the current playing station

**Comment by tenzap** [comment]
Have you had a thought about this in the meantime ?
It could also be possible to set it to "<station> - welle.io" if you prefer to keep the welle.io name in the title.

**Comment by tenzap** [comment]
See #461 which you may prefer

**Comment by AlbrechtL** [comment]
I accepted https://github.com/AlbrechtL/welle.io/pull/461 instead.

**Pull request closed without merging**
