### PR TITLE
Readme: include Fedora package installation directions

### PR DESCRIPTION
**Pull request by marcusmueller**
There's a `welle-io` package for fedora on rpmfusion. It's been updated to 2.4 (this update is pending review, give it a week or two).

A good time to include installation instructions for fedora!

### CODE REVIEW

**Comment by marcusmueller** [comment]
edit, hm, for some reason rpmfusion's koji doesn't like me yet, still, should be done soon ^TM

**Comment by marcusmueller** [comment]
(this PR was made against master, since that's the github-configured default branch, and hence where the README.md comes from. Will gladly rebase against next, if more appropriate!)

**Review by AlbrechtL — APPROVED** [review]
Thanks!

**Comment by marcusmueller** [comment]
No, thank *you* for maintaining all this! Also, would you maybe cherry-pick this commit to `master`, so that the changes appears on the Github main page already now (instead of the next time you merge next->master)? Didn't want to open this PR against master directly, as PRs simply go to next, right?

**Pull request merged**
