### PR TITLE
Textual changes, 13A frequency fixed, German Translation

### PR DESCRIPTION
**Pull request by andimik**
Fixed frequency for 13A
Typos in Countries and Language fixed 
Mention s8 and s16be
German Translation continued

### CODE REVIEW

**Comment by AlbrechtL** [comment]
Thank you very much for the German language improvements!

**Comment by AlbrechtL** [comment]
Oh, I didn't realize that the "de_DE.qm" file is not updated. The QM-file is used by the compiler to include the translations into the application.

To update "de_DE.qm" follow this how to please: https://github.com/AlbrechtL/welle.io/wiki/Translating-welle.io

**Comment by andimik** [comment]
Will you do it or should I try?

**Comment by andimik** [comment]
ok, done, but there are some conflicts. No idea how to resolve them ...

**Comment by AlbrechtL** [comment]
What kind of conflicts? Are they resolved in #115?

**Comment by andimik** [comment]
Yes, finally :-)

**Pull request merged**
