### PR TITLE
(#601) FreeBSD Installation instructions

### PR DESCRIPTION
**Pull request by herrhotzenplotz**
As discussed in #601 , I added the instruction for installing the `welle.io` package from the ports (both building the package from sources or installing the prebuilt binary using pkg).

The CMake aproach is a bit less painful, so I added instructions for that (refer to the Ports Makefile, this is what I did there as well).

Please let me know if you have issues with the PR or if I should squash the commits.

### CODE REVIEW

**Review by AlbrechtL — APPROVED** [review]
Thanks!

**Review by AlbrechtL — CHANGES_REQUESTED** [review]
One small thing. Please change the PR to the next branch.

**Comment by herrhotzenplotz** [comment]
On 1/25/21 9:26 PM, Albrecht Lohofener wrote:
 > @AlbrechtL requested changes on this pull request.
 >
 > One small thing. Please change the PR to the next branch.
 >

Should be done.

I'd suggest to document this somewhere in a contribution guideline, as 
this would eliminate this barrier and possibly arising merge conflicts 
for future contributors.


-- 
Sent from Thunderbird@Triton / FreeBSD 13-ALPHA2

Please remember: https://useplaintext.email/#etiquette
Do NOT send me Microsoft Office documents. I will and cannot open them.

Nico Sonack <nsonack@outlook.com>

**Review by AlbrechtL — APPROVED** [review]

**Comment by AlbrechtL** [comment]
> I'd suggest to document this somewhere in a contribution guideline, as
this would eliminate this barrier and possibly arising merge conflicts
for future contributors.

Thanks for pointing this out!

**Pull request merged**
