### PR TITLE
Raspberry Pi Guide

### PR DESCRIPTION
**Pull request by FartherOut**
A guide for compiling welle.io for Raspberry Pi with the help of a cross compiling Qt environment.

### CODE REVIEW

**Comment by viktorgino** [comment]
Why cross-compile? using qemu you can chroot into a Raspbian image and compile the app to armhf using the available Qt libraries etc.

Here are the scripts I use for compiling my project for the Pi during developement: https://github.com/viktorgino/headunit-desktop/tree/master/scripts

**Comment by viktorgino** [comment]
more info on qemu : https://wiki.debian.org/RaspberryPi/qemu-user-static

**Comment by FartherOut** [comment]
Mainly because I didn't know about qemu.
But this is interesting stuff, thanks for bringing it to my attention.

**Comment by viktorgino** [comment]
@FartherOut let me know if you need any help with it, I'm happy for the scripts to be part of welle.io (not like you need permission with GPL 😃 ). I only suggest qemu, because it is PITA to compile Qt and can take a long time. With this solution you can compile my project in 1-2 minutes from zero and recompile & deploy under a minute.

**Comment by FartherOut** [comment]
Updated readme to include a link to the guide.

**Pull request merged**
