### PR TITLE
Updated German translation

### PR DESCRIPTION
**Pull request by andimik**

### CODE REVIEW

**Comment by andimik** [comment]
Tried to translate latest strings as well. Hope I understood the sense in some cases.

**Comment by andimik** [comment]
Rework of nearly all expressions, standardized them, for instance
device = Gerät
service = Sender

**Comment by andimik** [comment]
German PTy translation is from https://www.sony.de/electronics/support/res/manuals/4463/44631812M.pdf

**Comment by tenzap** [comment]
Just in case you are interested, I found the official french translations of the PTY in 
ETSI TS 101 756 V2.2.1 (2017-08) (page 23)
German is page 24 :)

**Comment by andimik** [comment]
Thanks for the hint! Updated again

**Pull request merged**
