### PR TITLE
Enable translation of strings from the input directory

### PR DESCRIPTION
**Pull request by tenzap**
Some of the strings in the files of the input directory are not translated and not detected by qtlinguist for translation.
This commit should enable the translation for these files.

### CODE REVIEW

**Comment by tenzap** [comment]
Add support for concatenated strings passed to "onMessage" by splitting them and adding an optional argument to the "onMessage" function

**Comment by tenzap** [comment]
I'm sorry I tried to fix the conflict but it's even worse.
I guess I will abandon, I don't understand how to do this, sorry. :/

**Comment by tenzap** [comment]
now you can accept the conflicting line in
src/welle-cli/webradiointerface.cpp 
The change from `text` to `fullText` is expected

**Comment by tenzap** [comment]
Oh ok, I didn't understand the file displayed in "resolve conflict" page actually was modifiable... :D
Should be fine now

**Comment by AlbrechtL** [comment]
> Add support for concatenated strings passed to "onMessage" by splitting them and adding an optional argument to the "onMessage" function

What is the reason for it?

**Comment by tenzap** [comment]
Some of the string to translated are a concatenation For example in  `src/input/raw_file.cpp` you have (2 args)

```
radioController.onMessage(message_level_t::Error,
                "Cannot open file " + fileName);
```

To have a right translation, this has to be split into this (2 args + 1 optional)

```
radioController.onMessage(message_level_t::Error,
QT_TRANSLATE_NOOP("CRadioController", "Cannot open file "), fileName);
```

Hence the change

**Pull request merged**
