### PR TITLE
gui: add support for MPRIS

### PR DESCRIPTION
**Pull request by tenzap**
MPRIS = Media Player Remote Interfacing Specification
https://specifications.freedesktop.org/mpris-spec/2.2/
( Requires #532 )

### CODE REVIEW

**Comment by tenzap** [comment]
It should, I tried it and it used to work
It can only work on a branch using with #532 merged.
Can we retrigger the build here ?

**Review by AlbrechtL — CHANGES_REQUESTED** [review]
There are to much files changed. Please try to separate the MPRIS support from the other features.

**Comment by tenzap** [comment]
Which other changes than MPRIS are you referring to ? This commit only contains changes related to full MPRIS support, all these files need to be changed (need for dbus, interface files and implementation of the commands...)

**Review by AlbrechtL — CHANGES_REQUESTED** [review]
In src/welle-gui/welle-gui.pro adapt your changes to Linux only please. Otherwiese the Windows and macOS build is broken,

**Comment by AlbrechtL** [comment]
> Which other changes than MPRIS are you referring to ? This commit only contains changes related to full MPRIS support, all these files need to be changed (need for dbus, interface files and implementation of the commands...)

Agreed!

**Comment by tenzap** [comment]
Should be fine now

**Review by AlbrechtL — APPROVED** [review]

**Pull request merged**
